# zengobox.yaml
core:
  # The proxy core binary to use: "clash", "sing-box", "xray", "v2fly", "hysteria"
  bin_name: "clash"
  bin_list:
    - sing-box
    - clash
    - xray
    - v2fly
    - hysteria
  # Optional: For clash, you can specify the variant (e.g. "mihomo")
  clash_option: "mihomo"
  # Custom configuration file names for each core
  config_names:
    clash: "config.yaml"
    sing-box: "config.json"
    xray: "config.json"
    v2fly: "config.json"
    hysteria: "config.yaml"

network:
  mode: "tproxy"
  tproxy_port: 9898
  redir_port: 9797
  ipv6: false
  quic_block: false

proxy:
  mode: "blacklist"
  packages: []
  gids: []
  ap_list:
    allow:
      - "ap+"
      - "wlan+"
      - "rndis+"
      - "swlan+"
      - "ncm+"
      - "eth+"
    ignore: []

process:
  user_group: "root:net_admin"
  max_restarts: 5
  restart_window: "5m"
  restart_backoff: "3s"

cgroup:
  memcg:
    enabled: false
    limit: "100M"
  cpuset:
    enabled: false
  blkio:
    enabled: false


subscription:
  clash_urls: []
  singbox_url: ""
  renew: false

geo:
  auto_update: false

schedule:
  enabled: false
  cron: "0 0,6,12,18 * * *"
  update_geo: false
  update_subscription: false

wifi:
  enabled: false
  use_on_wifi: false
  use_on_disconnect: true
  ssid_matching: false
  ssid_mode: "blacklist"
  ssid_list: []

log:
  level: "info"
  max_size: "1M"
  toast: true
